tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-dim": "#131313",
                "on-secondary-container": "#aeb9d0",
                "on-tertiary": "#502400",
                "primary": "#adc6ff",
                "on-background": "#e5e2e1",
                "on-primary-fixed": "#001a42",
                "outline-variant": "#424754",
                "on-primary-container": "#00285d",
                "primary-fixed-dim": "#adc6ff",
                "on-primary-fixed-variant": "#004395",
                "inverse-surface": "#e5e2e1",
                "surface-tint": "#adc6ff",
                "error-container": "#93000a",
                "surface-container-highest": "#353534",
                "tertiary-container": "#df7412",
                "inverse-primary": "#005ac2",
                "secondary-fixed-dim": "#bcc7de",
                "tertiary": "#ffb786",
                "surface-container-low": "#1c1b1b",
                "surface-container-high": "#2a2a2a",
                "primary-container": "#4d8eff",
                "surface-container-lowest": "#0e0e0e",
                "on-error-container": "#ffdad6",
                "on-error": "#690005",
                "surface-container": "#201f1f",
                "background": "#131313",
                "on-primary": "#002e6a",
                "on-surface-variant": "#c2c6d6",
                "on-tertiary-fixed-variant": "#723600",
                "on-tertiary-container": "#461f00",
                "error": "#ffb4ab",
                "secondary": "#bcc7de",
                "outline": "#8c909f",
                "on-tertiary-fixed": "#311400",
                "secondary-container": "#3e495d",
                "on-secondary-fixed": "#111c2d",
                "surface-bright": "#3a3939",
                "tertiary-fixed-dim": "#ffb786",
                "on-secondary-fixed-variant": "#3c475a",
                "on-secondary": "#263143",
                "surface": "#131313",
                "primary-fixed": "#d8e2ff",
                "tertiary-fixed": "#ffdcc6",
                "secondary-fixed": "#d8e3fb",
                "on-surface": "#e5e2e1",
                "surface-variant": "#353534",
                "inverse-on-surface": "#313030"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "container-max": "1280px",
                "lg": "24px",
                "gutter": "24px",
                "md": "16px",
                "xs": "4px",
                "base": "4px",
                "xl": "48px",
                "sm": "8px",
                "margin": "32px"
            },
            "fontFamily": {
                "display-lg-mobile": ["Montserrat"],
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Montserrat"],
                "headline-lg": ["Montserrat"],
                "body-lg": ["Inter"],
                "display-lg": ["Montserrat"],
                "headline-md": ["Montserrat"]
            },
            "fontSize": {
                "display-lg-mobile": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "900"}],
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "800"}],
                "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "display-lg": ["80px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "900"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
            }
        }
    }
}